/* Author: Justin T.
 * Course: CS 302
 * Date: 1/9/19
 * Assignment: Homework One
 * Implemented in CLion using C99
 *
 * Filter.c takes an input stream of floating point numbers and formats them into organized columns with a fixed
 * precision that is based off default values defined in the program, unless overriden.
 *
 * The possible places for the values to be overriden are:
 * 1.) filter.cfg
 * 2.) system environment variables
 * 3.) command line at runtime
 *
 * filter.cfg is found in the project sub-directory 'cmake-build-debug' so that it can be read from the compiled program
 * generated by CMake in CLion.
 * */
#include <stdio.h>   // scanf(), fscanf(), fprintf(), fopen()
#include <stdlib.h>  // atoi(), getenv()

int main(int argc, char* argv[]) {
    // Set default values.
    int columns = 3;
    int precision = 13;

    // Sets the values of columns & precision if there is a config file named "filter.cfg"
    FILE *file_pointer = fopen("filter.cfg", "r");
    if (file_pointer) {
        fscanf(file_pointer, "%d", &precision);
        fscanf(file_pointer, "%d", &columns);
    }

    // Check for environment variables & if they exist initialize local variables with their values.
    char *environment_variable = getenv("CS302HW1PRECISION");
    if (environment_variable) {
        precision = atoi(environment_variable);
    }

    environment_variable = getenv("CS302HW1COLUMNS");
    if (environment_variable) {
        columns = atoi(environment_variable);
    }

    // Get command line arguments & if they exist initialize local variables with their values.
    if (argc > 1) {
        precision = atoi(argv[1]);
    }

    if (argc > 2) {
        columns = atoi(argv[2]);
    }

    // Loop over input and format accordingly
    double input;
    int counter = 0;

    while (scanf("%lf", &input) != EOF) {
        // print the formatted output
        printf("%*.*f", precision + 5, precision, input);

        if (++counter >= columns) {
            printf("\n");
            counter = 0;
        } else {
            printf("  ");
        }
    }

    exit(EXIT_SUCCESS);
}